# Generated by Django 3.0 on 2023-03-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('ดช.', 'ดช.'), ('ดญ.', 'ดญ.'), ('นาย', 'นาย'), ('นส.', 'นส.')], max_length=10, null=True),
        ),
    ]
