# Generated by Django 3.0 on 2023-04-20 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20230419_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bloodgrp',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
